name: Financial Operations (FinOps) Check
on:
  pull_request:
    branches: [ main ]

jobs:
  infracost:
    name: Infracost Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Infracost
        uses: infracost/actions/setup@v3

      - name: Generate Cost Estimate
        run: |
          infracost breakdown --path . \
                              --format json \
                              --out-file /tmp/infracost.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Post Cost Comment
        if: github.event.pull_request
        run: |
          infracost comment github --path /tmp/infracost.json \
                                   --repo ${{ github.repository }} \
                                   --github-token ${{ github.token }} \
                                   --pull-request ${{ github.event.pull_request.number }} \
                                   --behavior update
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
